[package]
name = "sequential"
description = "A trait for producing sequences of items with an explicit termination value."
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
either = "1.9.0"

[dev-dependencies]
test-case = "3.2.1"
